name: Dependabot fetch metadata
on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: "${{ secrets.PAT_TOKEN }}"
      - name: test
        run: |
          echo ${{ steps.dependabot-metadata.outputs.dependency-names }}
          echo ${{ github.action_repository	 }}
          echo ${{ github.actor	}}
          echo ${{ steps.dependabot-metadata.outputs.dependency-type }}
          echo ${{ steps.dependabot-metadata.outputs.update-type }}
          echo ${{ steps.dependabot-metadata.outputs.updated-dependencies-json }}
          echo ${{ steps.dependabot-metadata.outputs.directory
          echo ${{ steps.dependabot-metadata.outputs.package-ecosystem }}
          echo ${{ steps.dependabot-metadata.outputs.target-branch }} 
          echo ${{ steps.dependabot-metadata.outputs.previous-version }}
          echo ${{ steps.dependabot-metadata.outputs.new-version }}
          echo ${{ steps.dependabot-metadata.outputs.alert-state }}
          echo ${{ steps.dependabot-metadata.outputs.ghsa-id }}
          echo ${{ github.event_name }}

        shell: bash
